// user_prefs.cpp — see user_prefs.hpp.
#include "liveplay/core/user_prefs.hpp"

#include "liveplay/audio/meter.hpp"
#include "liveplay/logger.hpp"
#include "liveplay/util/unicode_path.hpp"

#include <algorithm>
#include <cctype>
#include <fstream>

#if !defined(_WIN32)
#  include <sys/stat.h>
#endif

namespace liveplay::core {

namespace fs = std::filesystem;

namespace {

// A user id becomes a filename, so it has to be one. Ids are generated by
// UserStore as hex, but this store must not TRUST that: the id arrives here
// from a verified token, and a token is still input. Anything that is not
// [A-Za-z0-9_-] is refused rather than escaped, because an id containing a
// path separator is not a filename problem, it is a sign something upstream
// is wrong.
bool is_safe_id(const std::string& id) {
    if (id.empty() || id.size() > 64) return false;
    return std::all_of(id.begin(), id.end(), [](unsigned char c) {
        return std::isalnum(c) || c == '_' || c == '-';
    });
}

// #RGB / #RRGGBB. The accent colour is written straight into a CSS custom
// property by the client, so "validated" here means "cannot carry anything but
// a colour" rather than "looks about right".
bool is_hex_colour(const std::string& s) {
    if (s.size() != 4 && s.size() != 7) return false;
    if (s[0] != '#') return false;
    return std::all_of(s.begin() + 1, s.end(), [](unsigned char c) {
        return std::isxdigit(c);
    });
}

// One transport keybinding. The action NAME is not checked against a list —
// see the header for why — but the binding itself is, because a malformed one
// would be compared against a KeyboardEvent on every keystroke.
bool is_binding(const json& v) {
    if (!v.is_object()) return false;
    if (!v.contains("key") || !v["key"].is_string()) return false;
    const auto key = v["key"].get<std::string>();
    if (key.empty() || key.size() > 32) return false;
    for (const char* f : {"ctrlKey", "shiftKey", "altKey"}) {
        if (v.contains(f) && !v[f].is_boolean()) return false;
    }
    return true;
}

json clean_binding(const json& v) {
    return json{
        {"key",      v["key"]},
        {"ctrlKey",  v.value("ctrlKey",  false)},
        {"shiftKey", v.value("shiftKey", false)},
        {"altKey",   v.value("altKey",   false)},
    };
}

} // namespace

std::string_view UserPrefs::describe(Result r) {
    switch (r) {
        case Result::Ok:      return "ok";
        case Result::NoUser:  return "no signed-in user";
        case Result::IoError: return "the profile could not be written";
    }
    return "unknown";
}

// ---------------------------------------------------------------------------
// The rules, written out
// ---------------------------------------------------------------------------
json UserPrefs::sanitise(const json& in) {
    json out = json::object();
    if (!in.is_object()) return out;

    // theme — the only nested value. Each half is independent: choosing an
    // accent colour must not force a mode along with it.
    if (in.contains("theme") && in["theme"].is_object()) {
        const json& t = in["theme"];
        json theme = json::object();
        if (t.contains("mode") && t["mode"].is_string()) {
            const auto m = t["mode"].get<std::string>();
            if (m == "light" || m == "dark") theme["mode"] = m;
        }
        if (t.contains("accentColor") && t["accentColor"].is_string()) {
            const auto c = t["accentColor"].get<std::string>();
            if (is_hex_colour(c)) theme["accentColor"] = c;
        }
        if (!theme.empty()) out["theme"] = std::move(theme);
    }

    // meterMode — a real enum, because the server acts on this one: it decides
    // whether true-peak and loudness DSP run at all.
    if (in.contains("meterMode") && in["meterMode"].is_string()) {
        const auto m = in["meterMode"].get<std::string>();
        if (audio::is_meter_mode(m)) out["meterMode"] = m;
    }

    if (in.contains("uiScrollToPlaying") && in["uiScrollToPlaying"].is_boolean()) {
        out["uiScrollToPlaying"] = in["uiScrollToPlaying"];
    }

    // locale — a language tag, not a path or a sentence. Which tags the client
    // actually ships is the client's business; this only bounds the shape.
    if (in.contains("locale") && in["locale"].is_string()) {
        const auto l = in["locale"].get<std::string>();
        const bool ok = !l.empty() && l.size() <= 16 &&
            std::all_of(l.begin(), l.end(), [](unsigned char c) {
                return std::isalnum(c) || c == '-' || c == '_';
            });
        if (ok) out["locale"] = l;
    }

    // playbackKeys — a map of action name to binding, or to null for "this
    // action is deliberately unbound", which is a different thing from absent.
    // A single bad entry drops that entry, not the whole keymap: losing one
    // binding is recoverable, losing the map is the thing this store exists to
    // prevent.
    if (in.contains("playbackKeys") && in["playbackKeys"].is_object()) {
        json keys = json::object();
        for (const auto& [action, binding] : in["playbackKeys"].items()) {
            if (action.empty() || action.size() > 64) continue;
            if (binding.is_null())      keys[action] = nullptr;
            else if (is_binding(binding)) keys[action] = clean_binding(binding);
        }
        out["playbackKeys"] = std::move(keys);
    }

    return out;
}

// ---------------------------------------------------------------------------
// Disk
// ---------------------------------------------------------------------------
void UserPrefs::set_dir(fs::path p) {
    std::lock_guard lock{mutex_};
    dir_ = std::move(p);
}

fs::path UserPrefs::dir() const {
    std::lock_guard lock{mutex_};
    return dir_;
}

fs::path UserPrefs::file_for(const std::string& user_id) const {
    return dir_ / (user_id + ".json");
}

// Faults one profile in from disk. Caller holds mutex_. Returns true when the
// cache now holds a profile for this user.
bool UserPrefs::load_locked(const std::string& user_id) const {
    if (cache_.count(user_id)) return true;
    if (dir_.empty() || !is_safe_id(user_id)) return false;

    const fs::path file = file_for(user_id);
    std::error_code ec;
    if (!fs::exists(file, ec)) return false;

    try {
        std::ifstream in{file, std::ios::binary};
        if (!in) return false;
        json j;
        in >> j;
        if (!j.is_object()) throw std::runtime_error("not an object");
        cache_[user_id] = sanitise(j);
        corrupt_.erase(user_id);
        return true;
    } catch (const std::exception& e) {
        // Not fatal, and not silently replaced. One person's preferences are
        // not the server's ability to run a show, so this cannot refuse to
        // boot the way a corrupt users.json does — but it must not quietly
        // become an empty profile either, so the file is left alone until
        // something actually needs to write, and then moved aside.
        Logger::warn("UserPrefs: '{}' could not be read ({}); "
                     "this user starts from defaults and the file is kept",
                     util::path_to_utf8(file), e.what());
        corrupt_[user_id] = true;
        return false;
    }
}

std::optional<json> UserPrefs::find(const std::string& user_id) const {
    std::lock_guard lock{mutex_};
    if (!load_locked(user_id)) return std::nullopt;
    return cache_.at(user_id);
}

json UserPrefs::get_or_seed(const std::string& user_id, const json& seed) {
    {
        std::lock_guard lock{mutex_};
        if (load_locked(user_id)) return cache_.at(user_id);
    }
    const json cleaned = sanitise(seed);

    // An empty seed writes NOTHING, and that is load-bearing rather than
    // tidiness. Creating an empty file here would mean "this user has a
    // profile", and seeding only ever runs when they do not — so a sign-in
    // that happens before any project is open (the ordinary case: the client
    // reads preferences the moment its socket comes up) would permanently
    // consume the one chance this person had to inherit their own theme and
    // keymap from a 2.4 document. Nothing to save means still no profile, and
    // the next read with a project open does the migration properly.
    if (cleaned.empty()) return json::object();

    json out;
    // patch() on an absent profile creates it, so the seed is written by the
    // same path as every other change rather than by a second writer.
    if (patch(user_id, cleaned, &out) == Result::Ok) {
        Logger::info("UserPrefs: seeded a profile for user {} from the open project "
                     "({} value(s))", user_id, cleaned.size());
    }
    return out;
}

UserPrefs::Result UserPrefs::patch(const std::string& user_id, const json& p,
                                   json* out_profile) {
    const json clean = sanitise(p);

    std::lock_guard lock{mutex_};
    if (!is_safe_id(user_id)) return Result::NoUser;
    if (dir_.empty())         return Result::IoError;

    load_locked(user_id);
    json profile = cache_.count(user_id) ? cache_.at(user_id) : json::object();

    // A null clears the key. sanitise() drops nulls for everything except a
    // playbackKeys entry, so the clear has to be read off the raw patch.
    if (p.is_object()) {
        for (const auto& [k, v] : p.items()) {
            if (v.is_null()) profile.erase(k);
        }
    }
    for (const auto& [k, v] : clean.items()) {
        // theme merges rather than replaces, so setting an accent colour does
        // not drop the mode chosen an hour ago.
        if (k == "theme" && profile.contains("theme") && profile["theme"].is_object()) {
            for (const auto& [tk, tv] : v.items()) profile["theme"][tk] = tv;
        } else {
            profile[k] = v;
        }
    }

    const json previous = cache_.count(user_id) ? cache_.at(user_id) : json::object();
    cache_[user_id] = profile;

    json on_disk = profile;
    on_disk["schemaVersion"] = kUserPrefsSchemaVersion;

    if (!write_locked(user_id, on_disk)) {
        cache_[user_id] = previous;
        return Result::IoError;
    }
    if (out_profile) *out_profile = profile;
    return Result::Ok;
}

bool UserPrefs::write_locked(const std::string& user_id, const json& doc) const {
    const fs::path file = file_for(user_id);
    try {
        std::error_code ec;
        fs::create_directories(dir_, ec);

        // A file that failed to parse is moved aside, once, rather than
        // overwritten — it may be the only copy of a keymap somebody spent an
        // afternoon on, and it costs nothing to keep.
        if (corrupt_.count(user_id)) {
            fs::rename(file, fs::path{file.string() + ".corrupt"}, ec);
            if (ec) Logger::warn("UserPrefs: could not set aside the unreadable '{}'",
                                 util::path_to_utf8(file));
            else    Logger::info("UserPrefs: kept the unreadable profile as '{}.corrupt'",
                                 util::path_to_utf8(file));
            corrupt_.erase(user_id);
            ec.clear();
        }

        const fs::path tmp = file.string() + ".tmp";
        {
            std::ofstream out{tmp, std::ios::binary | std::ios::trunc};
            if (!out) return false;
            out << doc.dump(2);
            out.flush();
            if (!out) return false;
        }
#if !defined(_WIN32)
        // Owner-only, for the same reason users.json is: a keymap is a
        // description of what somebody's hands do. Same admission as there —
        // no Windows equivalent, because a half-done ACL that looks like
        // protection is worse than the note in server/README.md.
        ::chmod(tmp.string().c_str(), S_IRUSR | S_IWUSR);
#endif
        fs::rename(tmp, file, ec);
        if (ec) {
            fs::remove(tmp, ec);
            return false;
        }
        return true;
    } catch (const std::exception& e) {
        Logger::warn("UserPrefs: failed to write '{}': {}",
                     util::path_to_utf8(file), e.what());
        return false;
    }
}

UserPrefs::Result UserPrefs::forget(const std::string& user_id) {
    std::lock_guard lock{mutex_};
    if (!is_safe_id(user_id)) return Result::NoUser;
    cache_.erase(user_id);
    corrupt_.erase(user_id);
    if (dir_.empty()) return Result::Ok;

    std::error_code ec;
    fs::remove(file_for(user_id), ec);
    if (ec) {
        Logger::warn("UserPrefs: could not remove the profile for user {}", user_id);
        return Result::IoError;
    }
    return Result::Ok;
}

} // namespace liveplay::core
